# Generated by Django 3.2.9 on 2022-03-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220218_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
    ]
