# Generated by Django 3.2.9 on 2022-03-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220311_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('EXCHANGE', 'Študent'), ('MEMBER', 'Člen')], default='MEMBER', max_length=50),
        ),
    ]
