from .user_registration_exists_tests import UserRegistrationExistsAPITestCase
from .user_registration_unique_tests import UserRegistrationUniqueAPITestCase
from .user_detail_tests import UserDetailAPITestCase
from .user_update_tests import UserUpdateAPITestCase
