# Generated by Django 3.2.9 on 2022-01-19 19:06

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30, verbose_name='Názov')),
                ('address', models.CharField(max_length=500, verbose_name='Adresa')),
                ('city', models.CharField(max_length=500, verbose_name='Mesto')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Krajina')),
                ('cooperation_start', models.DateField(null=True, verbose_name='Začiatok spolupráce')),
                ('first_name', models.CharField(max_length=30, verbose_name='Krstné meno')),
                ('last_name', models.CharField(max_length=30, verbose_name='Priezvisko')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobilné číslo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Škola',
                'verbose_name_plural': 'Školy',
                'ordering': ['name'],
                'default_related_name': 'schools',
            },
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='exchanges_s_name_8df3bf_idx'),
        ),
    ]
