# Generated by Django 3.2.9 on 2022-01-31 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211129_0317'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='Krstné meno')),
                ('last_name', models.CharField(max_length=30, verbose_name='Priezvisko')),
                ('birth_date', models.CharField(max_length=500, verbose_name='Dátum narodenia')),
                ('address', models.CharField(max_length=500, verbose_name='Adresa')),
                ('home_country', django_countries.fields.CountryField(max_length=2)),
                ('residence_country', django_countries.fields.CountryField(max_length=2)),
                ('academic_year', models.IntegerField(null=True, verbose_name='Školský rok pobytu')),
                ('semester', models.CharField(max_length=10, verbose_name='Polrok pobytu')),
                ('start', models.DateField(null=True, verbose_name='Dátum začiatku')),
                ('end', models.DateField(null=True, verbose_name='Dátum konca')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobilné číslo')),
                ('university_name', models.CharField(blank=True, max_length=500, verbose_name='Univerzita názov')),
                ('university_country', models.CharField(blank=True, max_length=500, verbose_name='Univerzita krajina')),
                ('study_filed', models.CharField(blank=True, max_length=500, verbose_name='Študijný odbor')),
                ('profession', models.CharField(blank=True, max_length=500, verbose_name='Povolanie')),
                ('language', models.JSONField(verbose_name='Jazyky')),
                ('foreign_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_students', to='exchanges.school', verbose_name='Zahraničná škola')),
                ('home_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_students', to='exchanges.school', verbose_name='Domáca škola')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='profiles.memberprofile', verbose_name='Člen')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['-created'],
                'default_related_name': 'students',
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name'], name='exchanges_s_last_na_e24016_idx'),
        ),
    ]
