# Generated by Django 3.2.9 on 2022-02-02 16:56

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import sscm.exchanges.models.school


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_auto_20220131_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=50, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=django_countries.fields.CountryField(countries=sscm.exchanges.models.school.ExchangeCountries, max_length=2, verbose_name='Krajina'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='school',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Krstné meno'),
        ),
        migrations.AlterField(
            model_name='school',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Priezvisko'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Mobilné číslo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Školský rok pobytu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Krstné meno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Priezvisko'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('WINTER', 'Zimný'), ('SUMMER', 'Letný')], default='WINTER', max_length=10, verbose_name='Polrok pobytu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['semester'], name='exchanges_s_semeste_737ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['home_country'], name='exchanges_s_home_co_d8fc7b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['residence_country'], name='exchanges_s_residen_ace651_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['birth_date'], name='exchanges_s_birth_d_db7c5c_idx'),
        ),
    ]
