# Generated by Django 3.2.9 on 2022-02-03 19:14

from django.db import migrations
import django_countries.fields
import sscm.core.countries


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_auto_20220202_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'default_related_name': 'students', 'ordering': ['-created'], 'verbose_name': 'Študent', 'verbose_name_plural': 'Študenti'},
        ),
        migrations.AlterField(
            model_name='student',
            name='home_country',
            field=django_countries.fields.CountryField(countries=sscm.core.countries.ExchangeCountries, max_length=2, verbose_name='Domáca krajina'),
        ),
        migrations.AlterField(
            model_name='student',
            name='residence_country',
            field=django_countries.fields.CountryField(countries=sscm.core.countries.ExchangeCountries, max_length=2, verbose_name='Krajina pobytu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_country',
            field=django_countries.fields.CountryField(blank=True, countries=sscm.core.countries.ExchangeCountries, max_length=2),
        ),
    ]
