# Generated by Django 3.2.9 on 2022-02-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220216_1058'),
        ('exchanges', '0005_auto_20220218_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='member',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='status_changed',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='memberprofile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='students', serialize=False, to='profiles.memberprofile'),
            preserve_default=False,
        ),
    ]
