# Generated by Django 3.2.9 on 2022-02-28 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0014_folder_permission_choices'),
        ('exchanges', '0006_auto_20220218_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('document', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='filer.file', verbose_name='Dokument')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumenty',
                'ordering': ['document'],
                'default_related_name': 'documents',
            },
        ),
    ]
