# Generated by Django 3.2.9 on 2022-03-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0008_auto_20220311_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='name', max_length=30, verbose_name='Názov'),
            preserve_default=False,
        ),
    ]
