# Generated by Django 3.2.9 on 2022-03-17 12:16

from django.db import migrations, models
import django_countries.fields
import sscm.core.countries


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0009_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='university_country',
            field=django_countries.fields.CountryField(blank=True, countries=sscm.core.countries.ExchangeCountries, max_length=2, verbose_name='Krajina univerzity'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Názov univerzity'),
        ),
    ]
