# Generated by Django 3.2.9 on 2022-02-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20220203_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='language',
            field=models.CharField(choices=[('SK,', 'Slovenčina'), ('DE', 'Nemčina'), ('EN', 'Angličtina')], default='SK,', max_length=20, verbose_name='Jazyk'),
        ),
    ]
