# Generated by Django 3.2.9 on 2022-03-11 09:30

from django.db import migrations
import django_countries.fields
import sscm.core.countries


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_alter_sponsor_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='country',
            field=django_countries.fields.CountryField(countries=sscm.core.countries.SponsorCountries, max_length=2, verbose_name='Krajina'),
        ),
    ]
