# Generated by Django 3.2.9 on 2022-03-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_alter_sponsor_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'default_related_name': 'sponsors', 'ordering': ['name'], 'verbose_name': 'Sponzor', 'verbose_name_plural': 'Sponzori'},
        ),
        migrations.RemoveIndex(
            model_name='sponsor',
            name='sponsors_sp_first_n_d77246_idx',
        ),
        migrations.RemoveIndex(
            model_name='sponsor',
            name='sponsors_sp_last_na_536199_idx',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default='name', max_length=30, verbose_name='Názov'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum narodenia'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['name'], name='sponsors_sp_name_f3b95f_idx'),
        ),
    ]
