# Generated by Django 3.2.9 on 2021-11-29 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'default_related_name': 'group_profile', 'ordering': ['name'], 'verbose_name': 'Skupina', 'verbose_name_plural': 'Skupiny'},
        ),
        migrations.AlterModelOptions(
            name='individualprofile',
            options={'default_related_name': 'individual_profile', 'ordering': ['last_name'], 'verbose_name': 'Jednotlivec', 'verbose_name_plural': 'Jednotlivci'},
        ),
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'default_related_name': 'member', 'ordering': ['member_number'], 'verbose_name': 'Člen', 'verbose_name_plural': 'Členovia'},
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_profile', to=settings.AUTH_USER_MODEL, verbose_name='Užívateľské konto'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum narodenia'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Krstné meno'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Priezvisko'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=500, verbose_name='Zamestnanie'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='title_prefix',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titul pred menom'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='title_suffix',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titul za menom'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to=settings.AUTH_USER_MODEL, verbose_name='Užívateľské konto'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='address',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='city',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Obec'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='enter_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum vstupu'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Členské číslo'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_type',
            field=models.CharField(choices=[('BASIC', 'Riadny'), ('GROUP', 'Skupinový'), ('FOUNDER', 'Zakladajúci')], default='BASIC', max_length=10, verbose_name='Druh členstva'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='note',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='member', to='parishes.parish', verbose_name='Farnosť'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktívny'), ('INACTIVE', 'Neaktívny'), ('OUTAGE', 'Vyradený'), ('DECEASED', 'Zosnulý')], default='INACTIVE', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='zip',
            field=models.CharField(blank=True, max_length=100, verbose_name='PSČ'),
        ),
    ]
