# Generated by Django 3.2.9 on 2022-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211129_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum úmrtia'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='leave_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum vyradenia'),
        ),
    ]
