# Generated by Django 3.2.9 on 2022-03-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_memberprofile_parish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='member_type',
            field=models.CharField(choices=[('BASIC', 'Riadny'), ('GROUP', 'Skupinový'), ('FOUNDER', 'Zakladajúci'), ('EXCHANGE', 'Absolvent')], default='BASIC', max_length=10, verbose_name='Druh členstva'),
        ),
    ]
