# Generated by Django 3.2.9 on 2022-03-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_memberprofile_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktívny'), ('INACTIVE', 'Neaktívny'), ('OUTAGE', 'Vyradený'), ('DECEASED', 'Zosnulý')], default='ACTIVE', max_length=10, verbose_name='Status'),
        ),
    ]
