# Generated by Django 3.2.9 on 2022-03-11 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_alter_memberprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_profile', to=settings.AUTH_USER_MODEL, verbose_name='Užívateľské konto'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to=settings.AUTH_USER_MODEL, verbose_name='Užívateľské konto'),
        ),
    ]
