# Generated by Django 3.2.9 on 2022-02-16 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Krstné meno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Priezvisko')),
                ('birth_date', models.DateField(verbose_name='Dátum narodenia')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_notice', to=settings.AUTH_USER_MODEL, verbose_name='Užívateľ')),
            ],
            options={
                'verbose_name': 'Nahlásene úmrtie',
                'verbose_name_plural': 'Nahlásene úmrtia',
                'ordering': ['last_name'],
                'default_related_name': 'death_notice',
            },
        ),
        migrations.AddIndex(
            model_name='deathnotice',
            index=models.Index(fields=['first_name'], name='death_notic_first_n_fb7133_idx'),
        ),
        migrations.AddIndex(
            model_name='deathnotice',
            index=models.Index(fields=['last_name'], name='death_notic_last_na_47f6e0_idx'),
        ),
    ]
