# Generated by Django 3.2.9 on 2022-02-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Emial'), ('FIREBASE', 'Firebase')], default='EMAIL', max_length=20),
        ),
    ]
