# Generated by Django 3.2.9 on 2022-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'default_related_name': 'emails', 'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_created_5feed0_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created'], name='notificatio_created_38238e_idx'),
        ),
    ]
