# Generated by Django 3.2.9 on 2022-03-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deanship',
            options={'default_related_name': 'deanship', 'ordering': ['name'], 'verbose_name': 'Dekanát', 'verbose_name_plural': 'Dekanáty'},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'default_related_name': 'parish', 'ordering': ['name'], 'verbose_name': 'Farnosť', 'verbose_name_plural': 'Farnosti'},
        ),
        migrations.AlterField(
            model_name='deanship',
            name='diocese',
            field=models.CharField(max_length=5, verbose_name='Diecéza'),
        ),
        migrations.AlterField(
            model_name='deanship',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='deanship',
            name='short',
            field=models.CharField(max_length=5, verbose_name='Skratka'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='deanship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parish', to='parishes.deanship', verbose_name='Dekanát'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Názov'),
        ),
    ]
