# Generated by Django 3.2.9 on 2022-03-11 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('date', models.DateField(verbose_name='Dátum')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Suma')),
                ('method', models.CharField(choices=[('CASH', 'Hotovosť'), ('TRANSFER', 'Prevod na účet')], default='CASH', max_length=20, verbose_name='Platobná metóda')),
                ('document_number', models.CharField(max_length=500, verbose_name='Číslo dokladu')),
                ('gift', models.BooleanField(default=False)),
                ('membership', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Užívateľské konto')),
            ],
            options={
                'verbose_name': 'Platba',
                'verbose_name_plural': 'Platby',
                'ordering': ['-created'],
                'default_related_name': 'payments',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='payments_pa_user_id_be07d0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='payments_pa_date_f2f1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='payments_pa_method_70cfb8_idx'),
        ),
    ]
