# Generated by Django 3.2.9 on 2022-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'default_related_name': 'group_profile', 'ordering': ['-created'], 'verbose_name': 'Film', 'verbose_name_plural': 'Filmy'},
        ),
        migrations.AlterField(
            model_name='video',
            name='code',
            field=models.CharField(max_length=500, verbose_name='Kód videa'),
        ),
    ]
