# Generated by Django 3.2.9 on 2022-02-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_options'),
        ('video', '0002_auto_20220216_1058'),
    ]

    operations = [
    ]
