# Generated by Django 3.2.9 on 2022-02-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_merge_20220217_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'default_related_name': 'group_profile', 'ordering': ['-created'], 'verbose_name': 'Film', 'verbose_name_plural': 'Filmy'},
        ),
    ]
