# Generated by Django 3.2.9 on 2022-02-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('originaldata', '0002_alter_originalmember_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originalmember',
            options={'default_related_name': 'original_member', 'ordering': ['surname'], 'verbose_name': 'Pôvodné údaje členov', 'verbose_name_plural': 'Pôvodné údaje členov'},
        ),
    ]
