# Generated by Django 3.2.9 on 2022-02-16 15:07
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('originaldata', '0003_alter_originalmember_options'),
    ]

    operations = [
        UnaccentExtension()
    ]