# Generated by Django 3.2.9 on 2022-02-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parishes', '0001_initial'),
        ('originaldata', '0004_auto_20220216_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalmember',
            name='adresa',
            field=models.CharField(blank=True, max_length=500, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='cl_cislo',
            field=models.IntegerField(verbose_name='Členské číslo'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='datum_nar',
            field=models.DateField(null=True, verbose_name='Dátum narodenia'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='datum_vstupu',
            field=models.DateField(null=True, verbose_name='Dátum výstupu'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='druh_clenstva',
            field=models.CharField(blank=True, max_length=50, verbose_name='Druh členstva'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='farnost_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='original_member', to='parishes.parish', verbose_name='Farnosť'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Krstné meno'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='obec',
            field=models.CharField(blank=True, max_length=100, verbose_name='Obec'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='povolanie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Povolanie'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='poznamka',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='psc',
            field=models.CharField(blank=True, max_length=100, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Priezvisko'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='titul',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titul pred menom'),
        ),
        migrations.AlterField(
            model_name='originalmember',
            name='titul2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titul za menom'),
        ),
    ]
