# Generated by Django 3.2.9 on 2022-03-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20220311_1724'),
        ('originaldata', '0006_auto_20220311_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalmember',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='originalmember',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_member', to='profiles.memberprofile', verbose_name='Člen'),
        ),
    ]
